import { WindowItem } from "./types";

export const initialWindows: WindowItem[] = [
  {
    id: "about",
    title: "About Me (SimpleText)",
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    x: 60,
    y: 60,
    w: 520,
    h: 380,
    minW: 300,
    minH: 200,
    zIndex: 1,
  },
  {
    id: "projects",
    title: "Projects (Finder HD)",
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    x: 120,
    y: 100,
    w: 640,
    h: 420,
    minW: 400,
    minH: 300,
    zIndex: 1,
  },
  {
    id: "terminal",
    title: "MacTerminal",
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    x: 180,
    y: 140,
    w: 580,
    h: 400,
    minW: 350,
    minH: 220,
    zIndex: 1,
  },
  {
    id: "settings",
    title: "Control Panel",
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    x: 240,
    y: 180,
    w: 460,
    h: 380,
    minW: 350,
    minH: 250,
    zIndex: 1,
  },
  {
    id: "contact",
    title: "Mail Composer",
    isOpen: false,
    isMinimized: false,
    isMaximized: false,
    x: 300,
    y: 220,
    w: 500,
    h: 410,
    minW: 350,
    minH: 250,
    zIndex: 1,
  },
];
